const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const schema = fs.readFileSync(path.join(root, 'prisma/schema.prisma'), 'utf8');
const routes = fs.readFileSync(path.join(root, 'src/routes/operations-suite.routes.ts'), 'utf8');
const modules = fs.readFileSync(path.join(root, 'src/services/module-access.service.ts'), 'utf8');
const reset = fs.readFileSync(path.join(root, 'scripts/reset-test-data.js'), 'utf8');
const expectedModels = ['Sale','SaleItem','SalePayment','PackageOffer','ClientPackage','MembershipPlan','ClientMembership','GiftCard','Supplier','PurchaseOrder','TimeClockEntry','StaffGoal','PayrollRun','ClinicalRecord','MarketingCampaign','ReviewRequest','Coupon','ClientPortalAccess','Organization','OrganizationLocation','BusinessResource','ResourceReservation','CostCenter','CashSession','ReceivablePayable','FinancialReconciliation','FiscalDocument'];
const expectedModules = ['POS','PACOTES','COMPRAS','EQUIPE','CLINICO','MARKETING','PORTAL_CLIENTE','MULTIUNIDADE','RECURSOS','FINANCEIRO_ADV'];
const expectedRouteFragments = ['/admin/pos/sales','/admin/customer-plans','/admin/procurement','/admin/team-management','/admin/clinical-records','/admin/marketing','/admin/client-portal/access','/admin/organizations','/admin/resources','/admin/finance-advanced','/client-portal/:token/overview'];
test('Marcos 25–34 possuem modelos Prisma canônicos', () => { for (const model of expectedModels) assert.match(schema, new RegExp(`model\\s+${model}\\s+\\{`), `modelo ausente: ${model}`); });
test('Marcos 25–34 possuem contratos HTTP registrados', () => { for (const fragment of expectedRouteFragments) assert.ok(routes.includes(fragment), `rota ausente: ${fragment}`); assert.ok(routes.includes('getTenant(request)'), 'rotas devem derivar tenant do JWT'); });
test('Entitlements incluem todos os novos módulos', () => { for (const module of expectedModules) assert.ok(modules.includes(`'${module}'`), `entitlement ausente: ${module}`); });
test('Limpeza controlada conhece todos os novos domínios persistentes', () => { const delegates = ['salePayment','saleItem','sale','clientPackage','packageOffer','clientMembership','membershipPlan','giftCard','purchaseOrder','supplier','timeClockEntry','staffGoal','payrollRun','clinicalRecord','marketingCampaign','reviewRequest','coupon','clientPortalAccess','organizationLocation','organization','resourceReservation','businessResource','fiscalDocument','financialReconciliation','receivablePayable','cashSession','costCenter']; for (const delegate of delegates) assert.ok(reset.includes(`['${delegate}'`), `reset não cobre: ${delegate}`); });
test('PDV possui baixa de estoque e lançamento financeiro no mesmo fluxo', () => { assert.ok(routes.includes('quantity: { decrement: item.quantity }')); assert.ok(routes.includes("category: 'PDV'")); assert.ok(routes.includes("status: 'REFUNDED'")); });
test('Recursos físicos bloqueiam overbooking por capacidade', () => { assert.ok(routes.includes("status: 'RESERVED'")); assert.ok(routes.includes('conflicts >= resource.capacity')); });
test('Portal armazena somente hash do token', () => { assert.ok(schema.includes('tokenHash')); assert.ok(routes.includes("createHash('sha256')")); });
